name: mama
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: papa
        run: chmod u+x ./train.sh && ./train.sh

--------------------------------------------------------------------------------------------------
%cd /content
!rm -rf ./fairy_stockfish_train_client
!git clone https://github.com/Vincentzyx/fairy_stockfish_train_client
%cd ./fairy_stockfish_train_client
!python client.py --user MEIBING --threads 4 
